packages:
  - name: propelauth
    environment:
      PROPELAUTH_API_KEY: "${PROPELAUTH_API_KEY}"
      PROPELAUTH_URL: "${PROPELAUTH_URL}"
      PROPELAUTH_VERIFIER_KEY: "${PROPELAUTH_VERIFIER_KEY}"
      PROPELAUTH_ISSUER: "${PROPELAUTH_ISSUER}"
    functions:
      - name: create-access-token
        runtime: "nodejs:18"
        limits:
          memory: 1024
      - name: get-propelauth-user
        runtime: "nodejs:18"
        limits:
          memory: 1024
      - name: validate-jwt-get-user
        runtime: "nodejs:18"
        limits:
          memory: 1024
      - name: validate-jwt-get-user-with-org-info
        runtime: "nodejs:18"
        limits:
          memory: 1024
      - name: validate-jwt-get-user-with-org-info-with-permission
        runtime: "nodejs:18"
        limits:
          memory: 1024
  - name: sample
    functions:
      - name: get-with-query
        runtime: "nodejs:18"
        limits:
          memory: 256
      - name: post-with-body
        runtime: "nodejs:18"
        limits:
          memory: 256
